### ISSUE TITLE
Update Renaming Script to Also Repackage Files

### ISSUE THREAD

**Issue by nicolemah99** [acep-uaf/camio-meter-streams#187]
We need to enhance the renaming script to not only rename the created event file zips but also handle the entire process of unzipping, renaming, and repackaging them. This is essential to ensure that the directory is correctly renamed when the directory is unzipped.

Original Issue: #169 

**Tasks**
- [x] Unzip the original event directory
- [x] Rename the original dir to `LOCATION-TYPE-METER_ID-YYYYMM-EVENT_ID`
- [x] Zip the renamed directory into a new zip file with name `LOCATION-TYPE-METER_ID-YYYYMM-EVENT_ID`
